transform_ui = function() {
	tabItem(tabName = "Transform",
		fluidRow(
			column(width = 3
				, htmlOutput("manage_data_title_transform")
				, htmlOutput("transform_data_select_vars")
				, htmlOutput("transform_data_change_type")
				, uiOutput("transform_data_change_type_choices")
				, htmlOutput("transform_data_rename_variable")
				, uiOutput("transform_data_rename_variable_input")
				, uiOutput("transform_data_recode_variable")
				, uiOutput("transform_data_recode_variable_choices")
				, uiOutput("transform_data_recode_variable_input")
				, uiOutput("transform_data_create_missing_values")
				, uiOutput("transform_data_create_missing_values_choices")
				, uiOutput("transform_data_create_missing_values_options")
				, uiOutput("transform_data_create_missing_values_input")
				, uiOutput("transform_data_create_missing_values_input_numeric")
				, uiOutput("transform_data_create_missing_values_input_range")
				, uiOutput("transform_data_identify_outliers")
				, uiOutput("transform_data_handle_outliers_choices")
				, uiOutput("transform_data_handle_outliers_correct_options")
				, uiOutput("transform_data_handle_outliers_correct_options_input")
				, uiOutput("transform_data_handle_missing_values")
				, uiOutput("transform_data_handle_missing_values_choices")
				, uiOutput("transform_data_handle_missing_values_options")
				, uiOutput("transform_data_handle_missing_values_new_category")
				, uiOutput("transform_data_handle_missing_values_new_numeric")
				, uiOutput("transform_data_apply")
			)
			, column(width=9,
				fluidRow(
					column(width=4
						, htmlOutput("transform_data_plot_missing_data_out_ui")
						, plotOutput("transform_data_plot_missing_data_out")
						, htmlOutput("transform_data_variable_type_ui")
						, verbatimTextOutput("transform_data_variable_type")
						, htmlOutput("transform_data_variable_type_log_ui")
						, verbatimTextOutput("transform_data_variable_type_log")
						, htmlOutput("transform_data_renamed_variable_log_ui")
						, verbatimTextOutput("transform_data_renamed_variable_log")
						, htmlOutput("transform_data_recoded_variable_labels_log_ui")
						, verbatimTextOutput("transform_data_recoded_variable_labels_log")
						, htmlOutput("transform_data_create_missing_values_log_ui")
						, verbatimTextOutput("transform_data_create_missing_values_log")
						, htmlOutput("transform_data_handle_outliers_log_ui")
						, verbatimTextOutput("transform_data_handle_outliers_log")
					)
					, column(width=8
						, htmlOutput("transform_data_quick_explore_ui")
						, verbatimTextOutput("transform_data_quick_explore_out")
						, htmlOutput("transform_data_handle_missing_values_ui")
						, verbatimTextOutput("transform_data_handle_missing_values_out")
						, plotlyOutput("transform_data_quick_plot_out")
					)
				)
			)
		)
	)
}
